spring:
  application:
    name: Demo Authorization Server
  autoconfigure: # prevents spring from showing default user password in logs on startup
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimumIdle: 2
      maximumPoolSize: 5
      max-lifetime: 2000000
      connectionTimeout: 30000
      idle-timeout: 30000
  sql:
    init:
      platform: postgres
      mode: always
  flyway:
    baseline-on-migrate: true
    sql-migration-prefix: v

server:
  port: 9000
  error:
    include-message: always
    include-binding-errors: never
    include-exception: false
  tomcat:
    accesslog:
      enabled: true
  shutdown: graceful

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, metrics, prometheus, flyway

oauth-clients:
  client-one:
    client-id: ${CLIENT_ONE_ID}
    client-secret: ${CLIENT_ONE_SECRET}
    scopes:
      - "endpoint-one"
  client-two:
    client-id: ${CLIENT_TWO_ID}
    client-secret: ${CLIENT_TWO_SECRET}
    scopes:
      - "endpoint-two"

security:
  issuer-uri: "http://authorization-server:9000"
  authorization-server-private-key: ${AUTHORIZATION_SERVER_PRIVATE_KEY}
  authorization-server-public-key: ${AUTHORIZATION_SERVER_PUBLIC_KEY}
